version: "2"
services:
  db:
    image: postgres:9
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
  rails:
    image: yock/mikeyockey-rails:latest
    ports:
      - "80:3000"
networks:
  backend:

volumes:
  db-data:
