---
- hosts: all
  remote_user: myockey
  vars_files:
    - vault.yml
  tasks:
    - name: Clone project repo
      git:
        repo: ssh://git@github.com/yock/mikeyockey-rails.git
        dest: ~/src

    - name: Pull Docker image for database
      docker_image:
        name: postgres:9

    - name: Pull Docker image for site
      docker_image:
        name: yock/mikeyockey-rails:latest
        force: yes

    - name: Start Database
      docker_container:
        name: postgres
        image: postgres:9
        published_ports:
          - 5432:5432
        volumes:
          - /var/lib/postgresql/data

    - name: Run database migrations
      docker_container:
        name: migrations
        image: yock/mikeyockey-rails
        command: db:migrate
        detach: no
        links:
          - "postgres:postgres"
        env:
          RAILS_ENV: production
          SECRET_KEY_BASE: "{{ secret_key_base }}"
          RAILS_LOG_TO_STDOUT: true

    - name: Start app
      docker_container:
        name: rails
        image: yock/mikeyockey-rails
        command: server
        log_driver: journald
        published_ports:
          - 80:3000
        links:
          - "postgres:postgres"
        env:
          RAILS_ENV: production
          SECRET_KEY_BASE: "{{ secret_key_base }}"
          RAILS_LOG_TO_STDOUT: true
